### ISSUE TITLE
go run main.go -bindings true

### ISSUE THREAD

**Issue by mouhib539** [jrkb6/portal-protocol#2]
I'm facing an issue with the go run main.go -bindings true command and could use some guidance. Here's what's happening:

I'm running Ganache CLI v6.12.2 with the correct environment settings.

When I execute go run main.go -bindings true, I expect it to generate Solidity files, but nothing happens.

I've checked my configurations, and everything seems to be in order.

I'm using the correct mnemonic and HD wallet path as specified in the documentation.

The command runs without errors, but the Solidity files are not generated in the expected directories (go-sdk/contracts/IdentityInterface/, go-sdk/contracts/IdentityManager/, go-sdk/contracts/IdentityRegistry/).

Any insights or suggestions would be greatly appreciated. Thank you!

**Comment by jrkb6** [comment]
Hi,

I noticed the contract code is missing. Bindings command generates Go metadata for the solidity classes to interact with contracts.

Now, contracts solidity code is available under the `./contracts/` folder. Please check out the main and try again.

**Comment by mouhib539** [comment]
hey pls can u contact me i want to ask u something abt this project 
i sent u a request on the instagram
